import { CalendarDays,Clock3,Tags } from 'lucide-react';
import { daysUntil,asArray } from '@/lib/speaking';
import PlaceBreakdown from './PlaceBreakdown';
import MonthBreakdown from './MonthBreakdown';
export default function Dashboard({items,onSelect}){
  const today=new Date().toISOString().slice(0,10), now=new Date(), monthStart=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10), monthEnd=new Date(now.getFullYear(),now.getMonth()+1,1).toISOString().slice(0,10), upcoming=items.filter(x=>x.speaking_date>=today&&x.status!=='Completed'), thisMonth=items.filter(x=>{const d=x.speaking_date||x.deploy_date;return d&&d>=monthStart&&d<monthEnd});
  const urgent=upcoming.filter(x=>x.progress!=='Ready to Deploy'&&daysUntil(x.speaking_date)<=14);
  const types=items.reduce((a,x)=>{asArray(x.presentation_type).forEach(t=>{a[t]=(a[t]||0)+1});return a},{}),top=Object.entries(types).sort((a,b)=>b[1]-a[1])[0];
  const cards=[{icon:CalendarDays,label:'Upcoming engagements',value:thisMonth.length,note:'This month'},{icon:Clock3,label:'Upcoming deadlines',value:urgent.length,note:'Within 14 days'},{icon:Tags,label:'Top presentation type',value:top?.[1]||0,note:top?.[0]||'No type set'}];
  return <section className="space-y-7"><div><h2 className="mb-3 font-display text-lg font-semibold">A Quick Look</h2><div className="grid gap-3 md:grid-cols-3">{cards.map(({icon:Icon,label,value,note},i)=><article key={label} className={`rounded-lg border border-[#D6DAE3] border-l-4 ${i===1?'border-l-[#B43A2E]':i===2?'border-l-[#D9A404]':'border-l-[#1B2A4B]'} bg-white p-5 shadow-sm transition hover:-translate-y-0.5`}><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-[#5A6781]"><Icon className="h-4 w-4"/>{label}</div><p className="mt-3 font-display text-4xl font-bold">{value}</p><p className="mt-1 text-xs text-[#5A6781]">{note}</p></article>)}</div></div><div className="grid gap-4 md:grid-cols-2"><PlaceBreakdown items={items} onSelect={onSelect}/><MonthBreakdown items={items}/></div></section>}