import { useEffect,useRef,useState } from 'react';
import { MapContainer,Marker,Popup,TileLayer,useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';
import { asArray } from '@/lib/speaking';
const upcomingIcon=L.divIcon({html:'<div style="width:18px;height:18px;background:#D9A404;border:2px solid #FFFFFF;border-radius:50% 50% 50% 0;transform:rotate(-45deg);box-shadow:0 2px 4px #1B2A4B66"></div>',className:'',iconSize:[20,20],iconAnchor:[10,20]});
const pastIcon=L.divIcon({html:`<img src="https://media.base44.com/images/public/6a60116b6ae7a4bd8b520b63/76e4a21d0_Icon.png" style="width:26px;height:26px;border-radius:50%;object-fit:cover"/>`,className:'',iconSize:[26,26],iconAnchor:[13,13]});
const todayStr=new Date().toISOString().slice(0,10);
const isPast=x=>(x.status==='Completed')||(!!x.speaking_date&&x.speaking_date<todayStr);
function Fit({points}){const map=useMap();useEffect(()=>{if(!points.length)return;const id=setTimeout(()=>{if(!map||!map._loaded)return;if(points.length>1){map.fitBounds(L.latLngBounds(points),{padding:[40,40],animate:true})}else{map.setView(points[0],5,{animate:true})}},0);return()=>clearTimeout(id)},[points]);return null}
function FocusController({focusItem,markerRefs}){const map=useMap();useEffect(()=>{if(!focusItem?.item)return;const lat=Number(focusItem.item.latitude);const lng=Number(focusItem.item.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;map.setView([lat,lng],13,{animate:true});const key=`${lat},${lng}`;const m=markerRefs.current[key];let id;if(m)id=setTimeout(()=>m.openPopup(),400);return()=>clearTimeout(id)},[focusItem?.nonce]);return null}
function PinZoomController({zoomTarget}){const map=useMap();useEffect(()=>{if(!zoomTarget||!map._loaded)return;const cur=map.getZoom();if(cur>=16){map.setView(zoomTarget.pos,5,{animate:true})}else{map.setView(zoomTarget.pos,16,{animate:true})}},[zoomTarget]);return null}
function TeardownGuard(){const map=useMap();useEffect(()=>()=>{try{L.Util.cancelAnimFrame(map._zoomAnim);map._zoomAnim=null;map._panAnim=null;if(map._mapPane){L.DomUtil.removeClass(map._mapPane,'leaflet-zoom-anim');L.DomEvent.off(map._mapPane,L.DomUtil.TRANSITION_END,map._onZoomTransitionEnd,map);}map._onZoomTransitionEnd=function(){};}catch(e){}},[map]);return null}
export default function EngagementMap({items,onView,focusItem}){const markerRefs=useRef({});const [zoomTarget,setZoomTarget]=useState(null);
  const located=items.filter(x=>x.latitude!==''&&x.latitude!=null&&x.longitude!==''&&x.longitude!=null&&Number.isFinite(Number(x.latitude))&&Number.isFinite(Number(x.longitude)));
  const groups=Object.values(located.reduce((acc,x)=>{const key=`${x.latitude},${x.longitude}`;if(!acc[key])acc[key]={lat:x.latitude,lng:x.longitude,address:x.address||'',items:[]};acc[key].items.push(x);return acc},{}));
  return <section className="overflow-hidden rounded-lg border border-[#D6DAE3] bg-white shadow-sm"><MapContainer center={[39.8,-98.6]} zoom={4} scrollWheelZoom={false} className="h-[320px] w-full"><TeardownGuard/><TileLayer attribution="Tiles © Esri" url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"/>{groups.map(g=><Marker key={`${g.lat},${g.lng}`} position={[g.lat,g.lng]} icon={g.items.every(isPast)?pastIcon:upcomingIcon} ref={r=>{if(r)markerRefs.current[`${g.lat},${g.lng}`]=r}} eventHandlers={{click:()=>{onView(g.items[0]);setZoomTarget({pos:[g.lat,g.lng],nonce:Date.now()})},mouseover:e=>e.target.openPopup(),mouseout:e=>e.target.closePopup()}}><Popup><div className="text-sm"><div className="font-semibold">{g.address}</div>{g.items[0].description&&<div className="mt-1"><span className="text-xs text-gray-700">{g.items[0].description}</span>{asArray(g.items[0].presentation_type).length>0&&<span className="text-xs text-gray-500"> — {asArray(g.items[0].presentation_type).join(', ')}</span>}</div>}{g.items.length>1&&<div className="mt-1 text-xs text-gray-500">+{g.items.length-1} more engagement{g.items.length-1>1?'s':''}</div>}</div></Popup></Marker>)}<FocusController focusItem={focusItem} markerRefs={markerRefs}/><PinZoomController zoomTarget={zoomTarget}/><Fit points={located.map(x=>[x.latitude,x.longitude])}/></MapContainer><div className="flex justify-between border-t border-[#D6DAE3] px-4 py-2 font-mono text-[11px] text-[#5A6781]"><span>{items.length} engagement{items.length===1?'':'s'}</span><span>{located.length} mapped</span></div></section>}